spring:
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_user
    password: your_password
    driver-class-name: org.postgresql.Driver

  application:
    name: user-manager-service
